name: run test

on:
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'gradle'
          cache-dependency-path: | # optional
              ./*.gradle*

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Running test
        run: ./gradlew clean testDebug
